In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [53]:
#Merging by columns
df1=DataFrame({'key':['X','Z','Y','Z','X','X'],'data1':np.arange(6)})
df1

data1 key
0      0   X
1      1   Z
2      2   Y
3      3   Z
4      4   X
5      5   X

In [54]:
df2 = DataFrame({'key':['Q','Y','Z'],'data2':[1,2,3]})
df2

data2 key
0      1   Q
1      2   Y
2      3   Z

In [55]:
pd.merge(df1,df2)

data1 key  data2
0      1   Z      3
1      3   Z      3
2      2   Y      2

In [6]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      1   Z      3
1      3   Z      3
2      2   Y      2

In [7]:
pd.merge(df1,df2,on='key',how='left')
# Uses key and index of the left dataset that is data1

data1 key  data2
0      0   X    NaN
1      1   Z    3.0
2      2   Y    2.0
3      3   Z    3.0
4      4   X    NaN
5      5   X    NaN

In [8]:
df1

data1 key
0      0   X
1      1   Z
2      2   Y
3      3   Z
4      4   X
5      5   X

In [9]:
pd.merge(df1,df2,on='key',how='right')

data1 key  data2
0    1.0   Z      3
1    3.0   Z      3
2    2.0   Y      2
3    NaN   Q      1

In [10]:
df2

data2 key
0      1   Q
1      2   Y
2      3   Z

In [11]:
pd.merge(df1,df2,on='key',how='outer')

data1 key  data2
0    0.0   X    NaN
1    4.0   X    NaN
2    5.0   X    NaN
3    1.0   Z    3.0
4    3.0   Z    3.0
5    2.0   Y    2.0
6    NaN   Q    1.0

In [13]:
df3 = DataFrame({'key': ['X', 'X', 'X', 'Y', 'Z', 'Z'],
                 'data_set_3': range(6)})
df4 = DataFrame({'key': ['Y', 'Y', 'X', 'X', 'Z'],
                 'data_set_4': range(5)})
df3

data_set_3 key
0           0   X
1           1   X
2           2   X
3           3   Y
4           4   Z
5           5   Z

In [14]:
df4

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [15]:
pd.merge(df3,df4)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [16]:
df_left = DataFrame({'key1': ['SF', 'SF', 'LA'],
                  'key2': ['one', 'two', 'one'],
                  'left_data': [10,20,30]})

#Dframe on right
df_right = DataFrame({'key1': ['SF', 'SF', 'LA', 'LA'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'right_data': [40,50,60,70]})

In [17]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [18]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [25]:
pd.merge(df_left,df_right,on=['key1','key2'])

key1 key2  left_data  right_data
0   SF  one         10          40
1   SF  one         10          50
2   LA  one         30          60

In [22]:
pd.merge(df_left,df_right,on=['key1','key2'],how='outer')

key1 key2  left_data  right_data
0   SF  one       10.0        40.0
1   SF  one       10.0        50.0
2   SF  two       20.0         NaN
3   LA  one       30.0        60.0
4   LA  two        NaN        70.0

In [26]:
pd.merge(df_left,df_right,on='key1')
# Pandas added a suffix to our other common columns

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [27]:
pd.merge(df_left,df_right,on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

In [28]:
# Merge on index
df_left=DataFrame({'key':['X','Y','Z','X','Y'],
                  'data': range(5)})
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [29]:
df_right = DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])
df_right

group_data
X          10
Y          20

In [36]:
pd.merge(df_left,df_right,left_on='key',right_index=True)

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20

In [40]:
df1=DataFrame({'key1':['SF','SF','SF','LA','LA'],
              'key2':[10,20,30,20,40],
              'dataset':np.arange(5.)})
df1

dataset key1  key2
0      0.0   SF    10
1      1.0   SF    20
2      2.0   SF    30
3      3.0   LA    20
4      4.0   LA    40

In [42]:
df2=DataFrame(np.arange(10).reshape(5,2),index=[['LA','LA','SF','SF','SF'],[20,10,10,10,20]],columns=['col_1','col_2'])
df2

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [44]:
pd.merge(df1,df2,left_on=['key1','key2'],right_index=True)

dataset key1  key2  col_1  col_2
0      0.0   SF    10      4      5
0      0.0   SF    10      6      7
1      1.0   SF    20      8      9
3      3.0   LA    20      0      1

In [46]:
df_left.join(df_right)

data key  group_data
0     0   X         NaN
1     1   Y         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Y         NaN

In [47]:

df_right

group_data
X          10
Y          20

In [48]:
df_left

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [49]:
df_right.join(df_left)

group_data  data  key
X          10   NaN  NaN
Y          20   NaN  NaN

In [2]:
#Concatenate

In [3]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)
# Concatenate in numpy

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
ser1=Series([0,1,2],index=['T','U','V'])
ser2=Series([3,4],index=['X','Y'])


In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
# Concatenate in pandas
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
# Produces dataframe
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
# Concatenate in dataframe

In [16]:
df1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
df1

X         Y         Z
0  0.561804  0.081788  0.336755
1  0.702995  0.182232 -0.416590
2 -0.412637  2.330177 -0.660513
3 -0.875913 -0.131726  0.033059

In [18]:
df2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [19]:
df2

Y         Q         X
0 -1.200080  0.635092  0.241819
1  0.822832  0.535134  2.281566
2  0.138809  0.460085  0.337348

In [22]:
df3=pd.concat([df1,df2],keys=['cat1','cat2'])

In [23]:
df3

Q         X         Y         Z
cat1 0       NaN  0.561804  0.081788  0.336755
     1       NaN  0.702995  0.182232 -0.416590
     2       NaN -0.412637  2.330177 -0.660513
     3       NaN -0.875913 -0.131726  0.033059
cat2 0  0.635092  0.241819 -1.200080       NaN
     1  0.535134  2.281566  0.822832       NaN
     2  0.460085  0.337348  0.138809       NaN

In [24]:
df3.index

MultiIndex(levels=[[u'cat1', u'cat2'], [0, 1, 2, 3]],
           labels=[[0, 0, 0, 0, 1, 1, 1], [0, 1, 2, 3, 0, 1, 2]])

In [35]:
df3.ix['cat1',0]

Q         NaN
X    0.561804
Y    0.081788
Z    0.336755
Name: (cat1, 0), dtype: float64

In [36]:
pd.concat([df1,df2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.561804  0.081788  0.336755
1       NaN  0.702995  0.182232 -0.416590
2       NaN -0.412637  2.330177 -0.660513
3       NaN -0.875913 -0.131726  0.033059
4  0.635092  0.241819 -1.200080       NaN
5  0.535134  2.281566  0.822832       NaN
6  0.460085  0.337348  0.138809       NaN

In [37]:
# Combining DataFrames

In [38]:
ser1=Series([2,np.nan,4,np.nan,6,np.nan],index=['Q','R','S','T','U','V'])

In [39]:
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [40]:
ser2=Series(np.arange(len(ser1)),dtype=np.float64,index=['Q','R','S','T','U','V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [41]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [42]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [44]:
df1 = DataFrame({'X': [1., np.nan, 3., np.nan],
                     'Y': [np.nan, 5., np.nan, 7.],
                     'Z': [np.nan, 9., np.nan, 11.]})
df2 = DataFrame({'X': [2., 4., np.nan, 6., 8.],
                     'Y': [np.nan, 10., 12., 14., 16.]})

In [45]:
df1

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [46]:
df2

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [47]:
df1.combine_first(df2)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

In [2]:
df1=DataFrame(np.arange(8).reshape(2,4),index=pd.Index(['LA','SF'],name="City"),columns=pd.Index(['A','B','C','D']
                                                                                                 ,name="Letters"))

In [4]:
df1

Letters  A  B  C  D
City               
LA       0  1  2  3
SF       4  5  6  7

In [10]:
df1_st=df1.stack()
df1_st

City  Letters
LA    A          0
      B          1
      C          2
      D          3
SF    A          4
      B          5
      C          6
      D          7
dtype: int32

In [11]:
df1_st.unstack()

Letters  A  B  C  D
City               
LA       0  1  2  3
SF       4  5  6  7

In [56]:
df1_st.unstack('Letters')

Letters  A  B  C  D
City               
LA       0  1  2  3
SF       4  5  6  7

In [57]:
df1_st.unstack('City')

City     LA  SF
Letters        
A         0   4
B         1   5
C         2   6
D         3   7

In [59]:
ser1 = Series([0,1,2],index=list("QXY"))
ser1

Q    0
X    1
Y    2
dtype: int64

In [60]:
ser2=Series([4,5,6],index=list("XYZ"))
ser2

X    4
Y    5
Z    6
dtype: int64

In [71]:
df=pd.concat([ser1,ser2],keys=['Alpha','Beta'])
df

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [72]:
df.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [74]:
df.unstack().stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [75]:
df=df.unstack()

In [76]:
df

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [77]:
df.stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [78]:
df.stack(dropna=False)

Alpha  Q    0.0
       X    1.0
       Y    2.0
       Z    NaN
Beta   Q    NaN
       X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [12]:
# Pivot

import pandas.util.testing as tm; tm.N = 3

#Create a unpivoted function
def unpivot(frame):
    N, K = frame.shape
    
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    
    # Return the DataFrame
    return DataFrame(data, columns=['date', 'variable', 'value'])

#Set the DataFrame we'll be using
dframe = unpivot(tm.makeTimeDataFrame())

In [13]:
dframe

date variable     value
0  2000-01-03        A -0.857507
1  2000-01-04        A  1.027518
2  2000-01-05        A -0.133380
3  2000-01-03        B -1.330874
4  2000-01-04        B -0.845818
5  2000-01-05        B  0.441266
6  2000-01-03        C -0.720943
7  2000-01-04        C  0.902890
8  2000-01-05        C -0.369157
9  2000-01-03        D  0.335231
10 2000-01-04        D  0.357495
11 2000-01-05        D -0.709325

In [19]:
dframe_piv = dframe.pivot('date','variable','value')

In [20]:
dframe_piv

variable           A         B         C         D
date                                              
2000-01-03 -0.857507 -1.330874 -0.720943  0.335231
2000-01-04  1.027518 -0.845818  0.902890  0.357495
2000-01-05 -0.133380  0.441266 -0.369157 -0.709325

In [23]:
dframe_piv.stack().unstack("date")

date      2000-01-03  2000-01-04  2000-01-05
variable                                    
A          -0.857507    1.027518   -0.133380
B          -1.330874   -0.845818    0.441266
C          -0.720943    0.902890   -0.369157
D           0.335231    0.357495   -0.709325

In [24]:
df=DataFrame({'key1': ['A'] * 2 + ['B'] * 3,
                  'key2': [2, 2, 2, 3, 3]})

In [25]:
df

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [26]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [27]:
df.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [28]:
df.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [29]:
df

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [31]:
df.drop_duplicates(['key1'],keep='last')

key1  key2
1    A     2
4    B     3

In [32]:
# Mapping

dframe = DataFrame({'city':['Alma','Brian Head','Fox Park'],
                    'altitude':[3158,3000,2762]})
dframe

altitude        city
0      3158        Alma
1      3000  Brian Head
2      2762    Fox Park

In [33]:
state_map={'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}
state_map

{'Alma': 'Colorado', 'Brian Head': 'Utah', 'Fox Park': 'Wyoming'}

In [34]:
dframe['State']=dframe['city'].map(state_map)
dframe

altitude        city     State
0      3158        Alma  Colorado
1      3000  Brian Head      Utah
2      2762    Fox Park   Wyoming

In [35]:
# Replace

ser1=Series([1,2,3,4,1,2,3,4])
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [36]:
ser1.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [37]:
ser1.replace([1,4],[100,400])
# List needs to match up

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [38]:
ser1.replace({1:1000,4:np.nan})

0    1000.0
1       2.0
2       3.0
3       NaN
4    1000.0
5       2.0
6       3.0
7       NaN
dtype: float64

In [40]:
# Rename Index

df=DataFrame(np.arange(12).reshape(3,4),index=['NY','LA','SF'],columns=['A','B','C','D'])
df

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [42]:
df.index.map(str.lower)

array(['ny', 'la', 'sf'], dtype=object)

In [43]:
df.index=df.index.map(str.lower)

In [44]:
df

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [45]:
df.rename(index=str.title,columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [48]:
df.rename(index={'ny':'New York'},columns={'A':'Alpha'},inplace=True)

In [49]:
df

Alpha  B   C   D
New York      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

In [50]:
# Binning

years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [51]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [53]:
cat=pd.cut(years,decade_bins)
cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, object): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [54]:
cat.categories

Index([u'(1960, 1970]', u'(1970, 1980]', u'(1980, 1990]', u'(1990, 2000]',
       u'(2000, 2010]', u'(2010, 2020]'],
      dtype='object')

In [56]:
pd.value_counts(cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [57]:
pd.cut(years,2,precision=1)

[(1969, 1992], (1969, 1992], (1969, 1992], (1992, 2015], (1992, 2015], ..., (1969, 1992], (1969, 1992], (1992, 2015], (1992, 2015], (1992, 2015]]
Length: 11
Categories (2, object): [(1969, 1992] < (1992, 2015]]

In [2]:
np.random.seed(12345)

In [3]:
df=DataFrame(np.random.randn(1000,4))

In [4]:
df

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.248944 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [5]:
df.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [6]:
col=df[0]

In [7]:
col

0     -0.204708
1      1.965781
2      0.769023
3      0.274992
4     -2.001637
5     -0.539741
6     -0.577087
7      0.000940
8     -2.370232
9     -1.265934
10    -2.359419
11    -1.307030
12     0.331286
13    -0.011862
14    -1.549106
15     0.862580
16     0.852965
17    -0.652469
18     0.723642
19    -0.622274
20     0.051316
21     1.010737
22    -0.131578
23    -0.114928
24     0.118110
25    -1.565657
26    -0.482573
27    -0.589488
28     0.929969
29     0.220487
         ...   
970    1.140886
971   -1.523554
972    0.097878
973   -0.738296
974   -1.969172
975   -0.813280
976    0.669147
977   -0.042541
978    0.615651
979    0.359400
980   -0.261844
981   -0.136429
982   -0.355393
983   -1.316005
984    0.675317
985   -0.754114
986   -0.105654
987   -0.052736
988   -0.172078
989    0.881601
990   -0.103672
991    0.926782
992   -0.527754
993    0.957144
994    1.221058
995    1.089085
996   -0.478509
997   -1.946267
998   -1.293122
999    0.089987
Name: 0, dtype: float64

In [8]:
df.ix[0]

0   -0.204708
1    0.478943
2   -0.519439
3   -0.555730
Name: 0, dtype: float64

In [9]:
df.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [10]:
df.iloc[0]

0   -0.204708
1    0.478943
2   -0.519439
3   -0.555730
Name: 0, dtype: float64

In [11]:
col[col>3]

900    3.366626
Name: 0, dtype: float64

In [12]:
col[np.abs(col)>3]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [14]:
df[(np.abs(df)>3).any(1)]
# any(1) to not get NaN values

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [15]:
df[(np.abs(df)>3)]=np.sign(df)*3

In [16]:
df.describe()
# as u can see we capped outliers

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [17]:
df=DataFrame(np.arange(16).reshape(4,4))

In [18]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [19]:
blender=np.random.permutation(4)

In [20]:
blender

array([1, 3, 2, 0])

In [21]:
df.take(blender)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3

In [23]:
box=np.array([1,2,3])

In [24]:
shaker=np.random.randint(0,len(box),size=10)

In [25]:
shaker

array([2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [26]:
shaker=np.random.randint(0,len(box),size=10)

In [27]:
shaker

array([2, 0, 2, 0, 0, 2, 1, 1, 2, 1])

In [28]:
grabs=box.take(shaker)

In [29]:
grabs

array([3, 1, 3, 1, 1, 3, 2, 2, 3, 2])