In [2]:
import numpy as np

In [3]:
l1=[1,2,3,4]

In [4]:
arr1=np.array(l1)

In [5]:
arr1

array([1, 2, 3, 4])

In [9]:
l2=[11,12,13,14]
l=[l1,l2]
arr2=np.array(l)
arr2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [10]:
arr2.shape

(2, 4)

arr2.dtype

In [11]:
arr2.dtype

dtype('int32')

In [14]:
np.zeros(5).dtype

dtype('float64')

In [18]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
np.empty(4)

array([ 0.,  0.,  0.,  0.])

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [29]:
from __future__ import division

In [30]:
5/2

2.5

In [33]:
arr1=np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [34]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [35]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [38]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [42]:
arr=np.arange(0,11)

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr=np.arange(0,11)
sliceArr=arr[0:6]
sliceArr

array([0, 1, 2, 3, 4, 5])

In [51]:
sliceArr[:100]=99
sliceArr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr
#Changes happened in the main array also, in Numpy we dont make new copys but get views of the array to save memory

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
# To make copy
copyArr=arr.copy()
copyArr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [62]:
arr_2d[2]

array([35, 40, 45])

In [65]:
arr3=np.zeros((10,10))
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [70]:
arr3.shape[0]

10

In [83]:
for i in range(arr3.shape[0]):
    arr3[i]=i
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [85]:
arr3[5]


array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [87]:
arr3[[4,6,2]]

array([[ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]])

In [79]:
t1=np.array([[1,2,3],[43,53,43]])

In [80]:
t1

array([[ 1,  2,  3],
       [43, 53, 43]])

In [81]:
t1[0]=1

In [82]:
t1

array([[ 1,  1,  1],
       [43, 53, 43]])

In [93]:
arr = np.arange(50).reshape(10,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [94]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [97]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [98]:
arr3d=np.arange(50).reshape(5,5,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [103]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [104]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [108]:
arr=np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [109]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

In [110]:
arr=np.arange(11)

In [111]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [113]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [114]:
# Binary Function
a=np.random.randn(10)

In [115]:
a

array([ 0.29272777, -0.72696838, -0.16372415, -0.37711184, -0.10006748,
       -1.12869672,  0.06260827,  0.46589796, -1.10478152, -0.24854617])

In [116]:
b=np.random.randn(10)
b

array([-1.81927602, -0.8384688 , -0.68753403, -0.17436567,  0.69250188,
       -0.71046059, -0.34555578,  0.06187546,  0.16714441, -0.24788788])

In [117]:
np.add(a,b)

array([-1.52654825, -1.56543718, -0.85125818, -0.55147751,  0.5924344 ,
       -1.83915731, -0.28294751,  0.52777342, -0.9376371 , -0.49643405])

In [119]:
np.maximum(a,b)

array([ 0.29272777, -0.72696838, -0.16372415, -0.17436567,  0.69250188,
       -0.71046059,  0.06260827,  0.46589796,  0.16714441, -0.24788788])

In [120]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [122]:
np.greater(a,b)

array([ True,  True,  True, False, False, False,  True,  True, False, False], dtype=bool)